# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value
    vk_api_creds: [5900438, OwEKI1Wt9Xmhi3LgDmSt]

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    download_picture_service:
        class: AppBundle\Consumer\DownloadPictureConsumer

    vk_service:
        class: BW\Vkontakte
        arguments: ["%vk_api_creds%"]